export function captureException(..._args: unknown[]) {}
