export function captureException(...args: unknown[]) {}
